# Generated by Django 3.2.20 on 2023-07-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
